// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IDM_API.Entities;

[Table("tbl_schedule")]
public partial class tbl_schedule
{
    [Key]
    public int ScheduleID { get; set; }

    [Required]
    [StringLength(255)]
    public string Title { get; set; }

    [Column(TypeName = "ntext")]
    public string Description { get; set; }

    public Guid? Organizer { get; set; }

    public TimeSpan StartTime { get; set; }

    [Column(TypeName = "decimal(8, 2)")]
    public decimal Duration { get; set; }

    public bool Repeat { get; set; }

    public bool OnWorkingDay { get; set; }

    [Required]
    [StringLength(255)]
    public string DayOfWeek { get; set; }

    public int WeekOfMonth { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedDateTime { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdatedDateTime { get; set; }

    [ForeignKey("Organizer")]
    [InverseProperty("tbl_schedules")]
    public virtual tbl_user OrganizerNavigation { get; set; }
}