// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IDM_API.Entities;

[Table("tbl_task")]
public partial class tbl_task
{
    [Key]
    public int TaskID { get; set; }

    [Required]
    [StringLength(255)]
    public string Title { get; set; }

    [Column(TypeName = "ntext")]
    public string Description { get; set; }

    [InverseProperty("Task")]
    public virtual ICollection<tbl_assignment> tbl_assignments { get; set; } = new List<tbl_assignment>();
}