// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IDM_API.Entities;

[Table("tbl_assignment")]
public partial class tbl_assignment
{
    [Key]
    public int AssignmentID { get; set; }

    public Guid? Employee { get; set; }

    public int? TaskID { get; set; }

    public TimeSpan StartTime { get; set; }

    public TimeSpan EndTime { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Deadline { get; set; }

    public int Status { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedDateTime { get; set; }

    public Guid? CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdatedDateTime { get; set; }

    public Guid? UpdatedBy { get; set; }

    [ForeignKey("CreatedBy")]
    [InverseProperty("tbl_assignmentCreatedByNavigations")]
    public virtual tbl_user CreatedByNavigation { get; set; }

    [ForeignKey("Employee")]
    [InverseProperty("tbl_assignmentEmployeeNavigations")]
    public virtual tbl_user EmployeeNavigation { get; set; }

    [ForeignKey("TaskID")]
    [InverseProperty("tbl_assignments")]
    public virtual tbl_task Task { get; set; }

    [InverseProperty("Assignment")]
    public virtual ICollection<tbl_progress> tbl_progresses { get; set; } = new List<tbl_progress>();
}