// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IDM_API.Entities;

[Table("tbl_department")]
public partial class tbl_department
{
    [Key]
    public int DepartmentID { get; set; }

    [Required]
    [StringLength(255)]
    public string DepartmentName { get; set; }

    [Required]
    [Column(TypeName = "ntext")]
    public string Description { get; set; }

    [InverseProperty("Department")]
    public virtual ICollection<tbl_discipline> tbl_disciplines { get; set; } = new List<tbl_discipline>();

    [InverseProperty("Department")]
    public virtual ICollection<tbl_user> tbl_users { get; set; } = new List<tbl_user>();
}