// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IDM_API.Entities;

[Table("tbl_progress")]
public partial class tbl_progress
{
    [Key]
    public int ProgressID { get; set; }

    public int? AssignmentID { get; set; }

    public int Status { get; set; }

    [Column(TypeName = "date")]
    public DateTime Date { get; set; }

    [ForeignKey("AssignmentID")]
    [InverseProperty("tbl_progresses")]
    public virtual tbl_assignment Assignment { get; set; }
}