// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IDM_API.Entities;

[Table("tbl_menu_role")]
public partial class tbl_menu_role
{
    [Key]
    public int MenuRoleID { get; set; }

    public int? MenuID { get; set; }

    public int? RoleID { get; set; }

    [ForeignKey("MenuID")]
    [InverseProperty("tbl_menu_roles")]
    public virtual tbl_menu Menu { get; set; }

    [ForeignKey("RoleID")]
    [InverseProperty("tbl_menu_roles")]
    public virtual tbl_role Role { get; set; }
}