// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IDM_API.Entities;

public partial class tbl_proposal
{
    [Key]
    public int ProposalsID { get; set; }

    [StringLength(100)]
    public string Title { get; set; }

    public Guid? UserID { get; set; }

    [Column(TypeName = "ntext")]
    public string Content { get; set; }

    public int? FileID { get; set; }

    public int Status { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedDateTime { get; set; }

    public Guid? CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdatedDateTime { get; set; }

    public Guid? UpdatedBy { get; set; }

    [ForeignKey("CreatedBy")]
    [InverseProperty("tbl_proposalCreatedByNavigations")]
    public virtual tbl_user CreatedByNavigation { get; set; }

    [ForeignKey("FileID")]
    [InverseProperty("tbl_proposals")]
    public virtual tbl_file File { get; set; }

    [ForeignKey("UpdatedBy")]
    [InverseProperty("tbl_proposalUpdatedByNavigations")]
    public virtual tbl_user UpdatedByNavigation { get; set; }

    [ForeignKey("UserID")]
    [InverseProperty("tbl_proposalUsers")]
    public virtual tbl_user User { get; set; }

    [InverseProperty("Proposal")]
    public virtual ICollection<tbl_approval> tbl_approvals { get; set; } = new List<tbl_approval>();
}