// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IDM_API.Entities;

[Table("tbl_file")]
public partial class tbl_file
{
    [Key]
    public int FileID { get; set; }

    [Required]
    [StringLength(255)]
    public string FileName { get; set; }

    [Column(TypeName = "text")]
    public string FilePath { get; set; }

    [StringLength(255)]
    public string DocumentType { get; set; }

    [StringLength(255)]
    public string FileType { get; set; }

    public int FileSize { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedDateTime { get; set; }

    public Guid? CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdatedDateTime { get; set; }

    public Guid? UpdatedBy { get; set; }

    [ForeignKey("CreatedBy")]
    [InverseProperty("tbl_fileCreatedByNavigations")]
    public virtual tbl_user CreatedByNavigation { get; set; }

    [ForeignKey("UpdatedBy")]
    [InverseProperty("tbl_fileUpdatedByNavigations")]
    public virtual tbl_user UpdatedByNavigation { get; set; }

    [InverseProperty("File")]
    public virtual ICollection<tbl_proposal> tbl_proposals { get; set; } = new List<tbl_proposal>();
}