// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IDM_API.Entities;

[Table("tbl_user")]
public partial class tbl_user
{
    [Key]
    public Guid UserID { get; set; }

    [StringLength(100)]
    public string UsernameOrEmail { get; set; }

    [Column(TypeName = "text")]
    public string PasswordHash { get; set; }

    [StringLength(255)]
    public string Fullname { get; set; }

    [StringLength(255)]
    public string Firstname { get; set; }

    [StringLength(255)]
    public string Lastname { get; set; }

    [Required]
    [StringLength(7)]
    public string Gender { get; set; }

    [Column(TypeName = "date")]
    public DateTime DateOfBirth { get; set; }

    public int Status { get; set; }

    public int Priority { get; set; }

    public int? DepartmentID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedDateTime { get; set; }

    public Guid? CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdatedDateTime { get; set; }

    public Guid? UpdatedBy { get; set; }

    [ForeignKey("CreatedBy")]
    [InverseProperty("InverseCreatedByNavigation")]
    public virtual tbl_user CreatedByNavigation { get; set; }

    [ForeignKey("DepartmentID")]
    [InverseProperty("tbl_users")]
    public virtual tbl_department Department { get; set; }

    [InverseProperty("CreatedByNavigation")]
    public virtual ICollection<tbl_user> InverseCreatedByNavigation { get; set; } = new List<tbl_user>();

    [InverseProperty("UpdatedByNavigation")]
    public virtual ICollection<tbl_user> InverseUpdatedByNavigation { get; set; } = new List<tbl_user>();

    [ForeignKey("UpdatedBy")]
    [InverseProperty("InverseUpdatedByNavigation")]
    public virtual tbl_user UpdatedByNavigation { get; set; }

    [InverseProperty("Approver")]
    public virtual ICollection<tbl_approval> tbl_approvals { get; set; } = new List<tbl_approval>();

    [InverseProperty("CreatedByNavigation")]
    public virtual ICollection<tbl_assignment> tbl_assignmentCreatedByNavigations { get; set; } = new List<tbl_assignment>();

    [InverseProperty("EmployeeNavigation")]
    public virtual ICollection<tbl_assignment> tbl_assignmentEmployeeNavigations { get; set; } = new List<tbl_assignment>();

    [InverseProperty("CreatedByNavigation")]
    public virtual ICollection<tbl_backup> tbl_backups { get; set; } = new List<tbl_backup>();

    [InverseProperty("CreatedByNavigation")]
    public virtual ICollection<tbl_file> tbl_fileCreatedByNavigations { get; set; } = new List<tbl_file>();

    [InverseProperty("UpdatedByNavigation")]
    public virtual ICollection<tbl_file> tbl_fileUpdatedByNavigations { get; set; } = new List<tbl_file>();

    [InverseProperty("CreatedByNavigation")]
    public virtual ICollection<tbl_proposal> tbl_proposalCreatedByNavigations { get; set; } = new List<tbl_proposal>();

    [InverseProperty("UpdatedByNavigation")]
    public virtual ICollection<tbl_proposal> tbl_proposalUpdatedByNavigations { get; set; } = new List<tbl_proposal>();

    [InverseProperty("User")]
    public virtual ICollection<tbl_proposal> tbl_proposalUsers { get; set; } = new List<tbl_proposal>();

    [InverseProperty("OrganizerNavigation")]
    public virtual ICollection<tbl_schedule> tbl_schedules { get; set; } = new List<tbl_schedule>();

    [InverseProperty("User")]
    public virtual ICollection<tbl_token> tbl_tokens { get; set; } = new List<tbl_token>();

    [InverseProperty("User")]
    public virtual ICollection<tbl_user_role> tbl_user_roles { get; set; } = new List<tbl_user_role>();
}