// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IDM_API.Entities;

[Table("tbl_user_role")]
public partial class tbl_user_role
{
    [Key]
    public int UserRoleID { get; set; }

    public int RoleID { get; set; }

    public Guid UserID { get; set; }

    [ForeignKey("RoleID")]
    [InverseProperty("tbl_user_roles")]
    public virtual tbl_role Role { get; set; }

    [ForeignKey("UserID")]
    [InverseProperty("tbl_user_roles")]
    public virtual tbl_user User { get; set; }
}