// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IDM_API.Entities;

public partial class tbl_discipline
{
    [Key]
    public int DesciplinesID { get; set; }

    [Required]
    [StringLength(255)]
    public string DisciplineName { get; set; }

    public int? DepartmentID { get; set; }

    [Column(TypeName = "ntext")]
    public string Description { get; set; }

    [ForeignKey("DepartmentID")]
    [InverseProperty("tbl_disciplines")]
    public virtual tbl_department Department { get; set; }
}