// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IDM_API.Entities;

[Table("tbl_token")]
public partial class tbl_token
{
    [Key]
    public int TokenID { get; set; }

    [Required]
    [StringLength(255)]
    public string Token { get; set; }

    public Guid? UserID { get; set; }

    public bool IsActive { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? RevokeAt { get; set; }

    [ForeignKey("UserID")]
    [InverseProperty("tbl_tokens")]
    public virtual tbl_user User { get; set; }
}