// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IDM_API.Entities;

[Table("tbl_backup")]
public partial class tbl_backup
{
    [Key]
    public int BackupID { get; set; }

    [Required]
    [StringLength(255)]
    public string BackupName { get; set; }

    [Required]
    [Column(TypeName = "text")]
    public string FilePath { get; set; }

    [Column(TypeName = "date")]
    public DateTime BackupDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedDateTime { get; set; }

    public Guid? CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdatedDateTime { get; set; }

    public Guid? UpdatedBy { get; set; }

    [ForeignKey("CreatedBy")]
    [InverseProperty("tbl_backups")]
    public virtual tbl_user CreatedByNavigation { get; set; }
}