// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IDM_API.Entities;

[Table("tbl_role")]
public partial class tbl_role
{
    [Key]
    public int RoleID { get; set; }

    [StringLength(255)]
    public string RoleName { get; set; }

    public int? RoleCode { get; set; }

    public bool IsActive { get; set; }

    public int Priority { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedDateTime { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdatedDateTime { get; set; }

    [InverseProperty("Role")]
    public virtual ICollection<tbl_menu_role> tbl_menu_roles { get; set; } = new List<tbl_menu_role>();

    [InverseProperty("Role")]
    public virtual ICollection<tbl_user_role> tbl_user_roles { get; set; } = new List<tbl_user_role>();
}