// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IDM_API.Entities;

[Table("tbl_approval")]
public partial class tbl_approval
{
    [Key]
    public int ProposalApprovals { get; set; }

    public int ProposalID { get; set; }

    public Guid? ApproverID { get; set; }

    public int? ApprovalStatus { get; set; }

    [Column(TypeName = "date")]
    public DateTime? ApprovalDate { get; set; }

    [ForeignKey("ApproverID")]
    [InverseProperty("tbl_approvals")]
    public virtual tbl_user Approver { get; set; }

    [ForeignKey("ProposalID")]
    [InverseProperty("tbl_approvals")]
    public virtual tbl_proposal Proposal { get; set; }
}